# Generated by Django 5.1.5 on 2025-01-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.AlterField(
            model_name='question',
            name='disciplines',
            field=models.ManyToManyField(related_name='questions', to='disciplines.discipline'),
        ),
    ]
