# Generated by Django 5.1.5 on 2025-01-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='response_types',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='question',
            name='citation',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('OBJ', 'Objetiva'), ('SUB', 'Subjetiva')], default='OBJ', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='questions.question')),
            ],
        ),
        migrations.DeleteModel(
            name='ResponseType',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
