# Generated by Django 5.1.5 on 2025-01-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisTIRAAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OBJ', 'Objetiva'), ('SUB', 'Subjetiva')], max_length=3)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to='SisTIRAAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('areas_of_study', models.ManyToManyField(related_name='disciplines', to='SisTIRAAPI.areaofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SisTIRAAPI.question')),
            ],
            bases=('SisTIRAAPI.question',),
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SisTIRAAPI.question')),
            ],
            bases=('SisTIRAAPI.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='disciplines',
            field=models.ManyToManyField(related_name='questions', to='SisTIRAAPI.discipline'),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('collaborators', models.ManyToManyField(related_name='collaborative_question_banks', to='SisTIRAAPI.user')),
                ('disciplines', models.ManyToManyField(related_name='question_banks', to='SisTIRAAPI.discipline')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_question_banks', to='SisTIRAAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_banks',
            field=models.ManyToManyField(blank=True, related_name='questions', to='SisTIRAAPI.questionbank'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField()),
                ('collaborators', models.ManyToManyField(related_name='collaborative_exams', to='SisTIRAAPI.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_exams', to='SisTIRAAPI.user')),
                ('questions', models.ManyToManyField(blank=True, related_name='exams', to='SisTIRAAPI.question')),
                ('question_banks', models.ManyToManyField(blank=True, related_name='exams', to='SisTIRAAPI.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('exams', models.ManyToManyField(related_name='rooms', to='SisTIRAAPI.exam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to='SisTIRAAPI.user')),
                ('participants', models.ManyToManyField(related_name='rooms', to='SisTIRAAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='SisTIRAAPI.statement'),
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='SisTIRAAPI.objectivequestion')),
            ],
        ),
    ]
